version: '3.1'
services:   
  dbpostgres:
    image: postgres:alpine3.14
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
